---
-
  name: 'はてなブックマーク - タグ検索 (5users)'
  url: 'http://b.hatena.ne.jp/search/tag?q=%s&users=5&mode=rss'
  title: 'タグ「%s」を検索 - はてなブックマーク'
  site_url: 'http://b.hatena.ne.jp/search/tag?q=%s&users=5'
  site_title: 'タグ「%s」を検索 - はてなブックマーク (5users)'
-
  name: 'はてなブックマーク - タグ検索 (1user)'
  url: 'http://b.hatena.ne.jp/search/tag?q=%s&users=1&mode=rss'
  title: 'タグ「%s」を検索 - はてなブックマーク'
  site_url: 'http://b.hatena.ne.jp/search/tag?q=%s&users=1'
  site_title: 'タグ「%s」を検索 - はてなブックマーク (1user)'
-
  name: 'はてなキーワード - 含むブログ'
  url: 'http://k.hatena.ne.jp/keywordblog/%s?mode=rss'
  title: '「%s」を含むブログ'
  site_url: 'http://k.hatena.ne.jp/keywordblog/%s'
  site_title: '「%s」を含むブログ - はてなキーワード'
-
  name: 'Google ブログ検索 (日本語)'
  url: 'http://www.google.co.jp/search?hl=ja&q=%s&lr=lang_ja&ie=utf-8&tbm=blg&tbs=sbd:1&output=atom'
  title: '%s - Google ブログ'
  site_url: 'http://www.google.co.jp/search?hl=ja&q=%s&lr=lang_ja&ie=utf-8&tbm=blg&tbs=sbd:1'
  site_title: '%s - Google ブログ検索'
-
  name: 'Google Blog Search (English)'
  url: 'http://www.google.com/search?hl=en&q=%s&lr=lang_en&ie=utf-8&tbm=blg&tbs=sbd:1&output=atom'
  title: '%s - Google Blog Search'
  site_url: 'http://www.google.com/search?hl=en&q=%s&lr=lang_en&ie=utf-8&tbm=blg&tbs=sbd:1'
  site_title: '%s - Google Blog Search'
-
  name: 'Twitter Search (日本語)'
  url: 'http://search.twitter.com/search.atom?q=%s&lang=ja'
  title: '%s - Twitter Search'
  site_url: 'https://twitter.com/search/%s%%20lang:ja'
  site_title: 'Twitter / Search - %s lang:ja'
-
  name: 'Twitter Search (English)'
  url: 'http://search.twitter.com/search.atom?q=%s&lang=en'
  title: '%s - Twitter Search'
  site_url: 'https://twitter.com/search/%s%%20lang:en'
  site_title: 'Twitter / Search - %s lang:en'
-
  name: 'Diigo - Tag'
  url: 'http://www.diigo.com/rss/tag/%s?tab=153'
  title: '%s on Diigo'
  site_url: 'http://www.diigo.com/tag/%s?tab=153'
  site_title: '%s | Diigo'
